server:
  port: 8280

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost/postgres}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_PASSWARD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

camel-app:
  simulationdate: ${SIMURATION_DATE:}
  