server:
  port: 8281

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost/postgres}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_PASSWARD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

camel-app:
  simulationdate: ${SIMURATION_DATE:}
  outputfilename: ${OUTPUT_FILENAME:shopping_put_data.txt}
  deletefilepath: ${DELETE_FILEPATH:data/shopping_put_data.txt}
